### ISSUE TITLE
FFにメトリクスを保持できるようにする

### ISSUE THREAD

**Issue by MaineK00n** [ehimetakahashilab/Eval-Fault-Detection-Probability#3]
## WHY
- 複数サイクルのため，FFもメトリクスを保持できる必要

## WHAT
- FFにメトリクスを保持できるようにする

## REF
#1

**Comment by MaineK00n** [comment]
@Aono082 FFが持つメトリクスとは？

**Comment by Aono082** [comment]
@MaineK00n 
欲しいデータは毎サイクルのFFにおけるBbCcおよびCOPの可制御性です。
